# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: seigerkornelyuk
open_collective: seiger-kornelyuk
ko_fi: seigerkornelyuk
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: seigerkornelyuk
issuehunt: seiger
otechie: # Replace with a single Otechie username
lfx_crowdfunding: 2518c0ee-423d-45a2-852e-f6539ed58058
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
